#!/bin/bash
##
## pentax version, using different aspect ratio than original
## storing original pictures to subfolder of photobooth_images
##
DIR="/home/pi/photobooth_images"
if [ -d "/mnt/hdd/photobooth_images" ]; then
   DIR="/mnt/hdd/photobooth_images"
fi
ARCH_DIR="/home/pi/PB_archive"
if [ -d "/mnt/hdd/PB_archive" ]; then
   ARCH_DIR="/mnt/hdd/PB_archive"
fi

suffix=$(date +%Y-%m-%d_%H%M%S)
mkdir $DIR/$suffix

echo "storing original pictures to $DIR/${suffix}/"
cp $DIR/*.jpg $DIR/${suffix}/

echo "resizing ..."
mogrify -resize 968x648 $DIR/*.jpg
##mogrify -resize 825x620 $DIR/*.jpg

echo "montage 2x2 pictures ..."
montage $DIR/*.jpg -tile 2x2 -geometry +10+10 /home/pi/temp_montage2.jpg

echo "montage label ..."
montage /home/pi/temp_montage2.jpg /home/pi/photobooth_label.jpg -tile 2x1 -geometry +5+5 /home/pi/temp_montage3.jpg

## needs border otherwise printer will crop all white edges and label
echo "adding  border ..."
convert /home/pi/temp_montage3.jpg -bordercolor white -border 20x60  /home/pi/temp_montage4.jpg

echo "sending to printer ..."
lp -d Canon_CP910 /home/pi/temp_montage4.jpg

echo "save montage in ${ARCH_DIR}/PB_${suffix}.jpg"
cp /home/pi/temp_montage4.jpg ${ARCH_DIR}/PB_${suffix}.jpg

echo "clean up ..."
rm ${DIR}/*.jpg
rm /home/pi/temp*

echo "done."
echo
